### PR TITLE
5.0.7 update

### PR DESCRIPTION
**Pull request by nelsonic**
Hi @iteles 
This mini update brings the example up to date with the latest version of Hapi.js
and adds detail to the readme answering a question asked in the **dwyl** chat: https://github.com/dwyl/hapi-auth-jwt2-example/issues/5#issue-107317694

### CODE REVIEW

**Comment by nelsonic** [comment]
@iteles please review/merge. and reply in the gitter chanel when done: https://gitter.im/dwyl/chat (_thanks_!) :sparkles:

**Comment by nelsonic** [comment]
Ok, I'll update the gitter chat then.

**Comment by iteles** [comment]
@nelsonic Sorry, our internet was down and I couldn't find my way back to this pull request on my mobile  (because github on mobile is rubbish) so I decided to wait til it was back up.
Thanks for doing that :+1:

**Comment by nelsonic** [comment]
_No worries mate_ ... :wink: 
Not having internet is so lame ... :toilet:

**Pull request merged**
